version: "3"

x-common-variables: &common-variables
  DB_USER: root
  DB_PASS: root
  DB_NAME: sampledb

services:
  mysql:
    image: mysql:5.7
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      LANG: C.UTF-8
    ports:
      - 3307:3306
    restart: unless-stopped
    volumes:
      - ./db/sample.sql:/docker-entrypoint-initdb.d/sample.sql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always

  server:
    build: ./server
    depends_on:
      - mysql
    expose:
      - 3000
    environment:
      <<: *common-variables
      DB_HOST: mysql
      DB_TOK: sptoken
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
      - /app/node_modules
    links:
      - mysql
    command: bash -c 'while !</dev/tcp/mysql/3306; do sleep 1; done; npm start'

  client:
    build: ./client    
    ports:
      - 4200:80
    volumes:
      - ./client/src:/app/src
    links:
      - server


    